development:
  adapter: mysql
  database: basecamp_status_development
  username: root

test: &test
  adapter: mysql
  database: basecamp_status_test
  username: root

production:
  adapter: mysql
  database: basecamp_status_production
  username: root
